travis:
  secure:
    BINSTAR_TOKEN: f/ZezTUj3qY5cHwBd6LvRC/y0MQzIBgAQnmX/1afW32+vtvpGZQHAs7eLAZVkJ+WBVk1XcBqKzJS8OaBmgWLEhVC8vChwBrGTvjd9PYcKxpCuXVoU6eX6QzlDrG9OV+RIyhfwMjnsUN4ROCQvTm0bNkn85HwUxKNWCLNVZWYZGDa8IkVszF7Q75BCZFvG6ZPsUUVNC6lI8/MSbxdOoMaIsUM9W3uJlTE/YTa0uGuH03/XJKqjY6WFTzskKlBHlHDjE79NUX+nonJLTwQWkA4h6rwvs+p8rYdki38/piuk64OjY2bwJO5RbxedltK8JsF2sPMs1mUerIwOIlOgwgzy8MVpJhuZBMeR2EXg1EUwme9KwMnB5a5e7uRWEZ0pv5w5sF5IbAi+Sq13B2XyVHMQZELMsj9jaJkcHhPyhR7n4/9KoRcmhH1ZupmgOTHwSkapWKN7kg36TKp6hgHfkI6Ew12/7yoxb+FIIENNkdEbn9DTtF3yswTzj1Och6bbHGqwkQYItACsR4Bolwa+VgipfSW0XRrKEcc4KN39jJ8hThH0HAdSHCEHUWqsb/BAZfZKWkbiiyBfUDaNfMGwdSE6jSm+T9bmHIe2Ef8qTN+D+OB+D+6KX8xnD5gA8eYMek0QAuxja7BUWGq1lgIRr40AtBXZHOqVI/uEGj5w7A8RuA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
